### ISSUE TITLE
Instructions unclear on how train/val/test trajectories are generated

### ISSUE THREAD

**Issue by hercky** [shengpu1126/RL-Set-Valued-Policy#1]
There are two notebooks in `1_preprocess` for generating `trajD_tr.pkl`, `trajD_va.pkl`, `trajD_te.pkl`. It is unclear which one between between `1_Z_reformat_data.ipynb` vs `1_Z_reformat_data_discrete.ipynb` is being used to generate those files. 

It looks like `1_Z_reformat_data_discrete.ipynb` is being used, but it'll be great if you can clarify this.

**Comment by shengpu-tang** [comment]
Hello, you are correct, `1_Z_reformat_data_discrete.ipynb` is used to generate dataset with the discrete state space. The other notebook `1_Z_reformat_data.ipynb` generates files named `traj_tr.pkl` (without the D) and those contain the state feature vectors.

**Comment by hercky** [comment]
Thank you so much for answering it! I missed the D in the name. Closing the issue!
